name: fastapi-env
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - fastapi
    - uvicorn[standard]
    - sqlalchemy
    - requests
    - structlog
    - poetry
    - alembic
    - pip
    - pip:
        - fastapi-sqla